#!/usr/bin/env python3
"""Milestone-log self-check.

Compiles runtime/milestone.c together with a driver and RUNS it, three times,
because the properties that matter are runtime ones:

  --off      PS3_MILESTONE_OUT unset -> the module is inert and writes nothing.
  --nodump   _exit(0), skipping atexit -> the ordered stream is still on disk.
             This is the "survives a hang" property, and it is the whole reason
             keys are appended as they are first seen instead of buffered.
  --on       normal exit -> stream, bucketed counts and scalars all present,
             with four threads hammering shared keys throughout.

The threaded part is not decoration. Lookups are lock-free and slots are
published with a release store; if that protocol is wrong the table hands back
truncated or duplicated keys under load, the gate starts reporting phantom
differences, and people learn to ignore it. So the check asserts that every key
got exactly one ordinal and that no key outside the expected set ever appears.
"""
import argparse
import os
import shutil
import subprocess
import sys

from msvc_env import find_vcvars

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRATCH = os.path.join(ROOT, "scratch")

# 4 threads x 1000 iterations over 8 keys = 500 hits each -> the "100-999" bucket.
N_THREADS, N_ITERS, N_KEYS = 4, 1000, 8
HITS_PER_KEY = N_THREADS * N_ITERS // N_KEYS

DRIVER = r"""
/* Generated by tools/test_milestone.py -- milestone log driver. */
#include "ps3emu/milestone.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#  include <windows.h>
   typedef HANDLE thr_t;
#else
#  include <pthread.h>
#  include <unistd.h>
   typedef pthread_t thr_t;
#endif

#define MS_CKPT_SECS 2   /* must match runtime/milestone.c */

#define N_THREADS %(N_THREADS)d
#define N_ITERS   %(N_ITERS)d
#define N_KEYS    %(N_KEYS)d

static const char* k_shared[N_KEYS] = {
    "t:zero", "t:one", "t:two", "t:three",
    "t:four", "t:five", "t:six", "t:seven"
};

static void worker_body(void)
{
    int i;
    for (i = 0; i < N_ITERS; i++)
        ps3_ms(k_shared[i %% N_KEYS]);
}

#ifdef _WIN32
static DWORD __stdcall worker(LPVOID p) { (void)p; worker_body(); return 0; }
#else
static void* worker(void* p) { (void)p; worker_body(); return NULL; }
#endif

int main(int argc, char** argv)
{
    const char* mode = argc > 1 ? argv[1] : "--on";
    thr_t th[N_THREADS];
    int i;

    /* Ordinals 1..3, with 'a' repeated so its bucket differs from the others. */
    ps3_ms("a");
    ps3_ms("b");
    for (i = 0; i < 5; i++) ps3_ms("a");
    ps3_ms("c");

    /* Formatted keys go through the same table. */
    ps3_msf("f:%%d", 7);

    ps3_ms_kv("scalar:answer", 42);
    ps3_ms_kv("scalar:answer", 43);   /* last value wins */
    ps3_ms_kv("scalar:big", 1234567890123LL);

    for (i = 0; i < N_THREADS; i++) {
#ifdef _WIN32
        th[i] = CreateThread(NULL, 0, worker, NULL, 0, NULL);
#else
        pthread_create(&th[i], NULL, worker, NULL);
#endif
    }
    for (i = 0; i < N_THREADS; i++) {
#ifdef _WIN32
        WaitForSingleObject(th[i], INFINITE);
        CloseHandle(th[i]);
#else
        pthread_join(th[i], NULL);
#endif
    }

    if (strcmp(mode, "--nodump") == 0) {
        /* What a watchdog kill looks like: keep working past the checkpoint
         * interval, then straight out with no atexit handlers. The counts on
         * disk have to come from the periodic checkpoint, not from the dump. */
#ifdef _WIN32
        Sleep(1000 * (MS_CKPT_SECS + 1));
#else
        sleep(MS_CKPT_SECS + 1);
#endif
        worker_body();
        fflush(NULL);
        _exit(0);
    }
    return 0;
}
"""


def build(driver_c, exe):
    """Compile the driver + the real milestone.c. Returns (ok, message)."""
    if os.name == "nt":
        clang = shutil.which("clang-cl") or r"C:\Program Files\LLVM\bin\clang-cl.exe"
        if not os.path.exists(clang) and not shutil.which("clang-cl"):
            return False, "clang-cl not found"
        vcvars = find_vcvars()
        if not vcvars:
            return False, "vcvars64.bat not found"
        bat = os.path.join(SCRATCH, "milestone_build.bat")
        log = os.path.join(SCRATCH, "milestone_build.log")
        with open(bat, "w") as f:
            f.write("@echo off\n")
            f.write('call "%s" >nul 2>nul\n' % vcvars)
            f.write('cd /d "%s"\n' % ROOT)
            f.write('"%s" /nologo /W3 /I include /Fe:"%s" "%s" runtime\\milestone.c '
                    '> "%s" 2>&1\n' % (clang, exe, driver_c, log))
        rc = subprocess.run(["cmd", "/c", bat], cwd=ROOT).returncode
        if rc != 0:
            return False, open(log).read() if os.path.exists(log) else "compile failed"
        return True, ""

    cc = os.environ.get("CC") or shutil.which("cc") or shutil.which("clang") or shutil.which("gcc")
    if not cc:
        return False, "no C compiler found (set CC)"
    cp = subprocess.run([cc, "-O1", "-w", "-I", "include", "-o", exe, driver_c,
                         os.path.join("runtime", "milestone.c"), "-lpthread"],
                        cwd=ROOT, capture_output=True, text=True)
    if cp.returncode != 0:
        return False, cp.stdout + cp.stderr
    return True, ""


def run(exe, mode, out_path):
    env = dict(os.environ)
    if out_path is None:
        env.pop("PS3_MILESTONE_OUT", None)
    else:
        env["PS3_MILESTONE_OUT"] = out_path
        if os.path.exists(out_path):
            os.remove(out_path)
    cp = subprocess.run([exe, mode], cwd=ROOT, env=env,
                        capture_output=True, text=True, timeout=120)
    return cp


def parse(path):
    """-> (ordered [(ord, key)], {key: bucket}, {key: value}, saw_end)"""
    stream, counts, kv, saw_end = [], {}, {}, False
    with open(path) as f:
        for line in f:
            line = line.rstrip("\n")
            if line == "# end":
                saw_end = True
                continue
            if line.startswith("#"):
                continue
            parts = line.split("\t")
            if parts[0] == "count":
                counts[parts[1]] = parts[2]
            elif parts[0] == "kv":
                kv[parts[1]] = int(parts[2])
            else:
                stream.append((int(parts[0]), parts[1]))
    return stream, counts, kv, saw_end


FAILURES = []


def check(cond, what):
    if cond:
        print("  ok   %s" % what)
    else:
        print("  FAIL %s" % what)
        FAILURES.append(what)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep", action="store_true", help="keep the built driver")
    args = ap.parse_args()

    os.makedirs(SCRATCH, exist_ok=True)
    driver_c = os.path.join(SCRATCH, "milestone_driver.c")
    exe = os.path.join(SCRATCH, "milestone_driver" + (".exe" if os.name == "nt" else ""))
    out = os.path.join(SCRATCH, "milestone_out.txt")

    with open(driver_c, "w") as f:
        f.write(DRIVER % dict(N_THREADS=N_THREADS, N_ITERS=N_ITERS, N_KEYS=N_KEYS))

    ok, msg = build(driver_c, exe)
    if not ok:
        # A green tick that compiled nothing is worse than a red one, so CI=1
        # turns a missing compiler into a failure rather than a skip.
        print("[milestone] BUILD FAILED: %s" % msg.strip()[:2000])
        return 2 if os.environ.get("CI") else 0

    expected_shared = {"t:zero", "t:one", "t:two", "t:three",
                       "t:four", "t:five", "t:six", "t:seven"}
    expected_all = {"a", "b", "c", "f:7"} | expected_shared

    # --- inert when unconfigured -------------------------------------------
    print("[milestone] --off (PS3_MILESTONE_OUT unset)")
    if os.path.exists(out):
        os.remove(out)
    cp = run(exe, "--on", None)
    check(cp.returncode == 0, "exits cleanly with the log disabled")
    check(not os.path.exists(out), "writes nothing when unconfigured")

    # --- the ordered stream survives a kill --------------------------------
    print("[milestone] --nodump (_exit, no atexit)")
    cp = run(exe, "--nodump", out)
    check(cp.returncode == 0, "driver ran")
    check(os.path.exists(out), "stream file exists after _exit")
    stream, counts, kv, saw_end = parse(out)
    check(len(stream) == len(expected_all),
          "all %d keys reached disk without a clean exit" % len(expected_all))
    check(not saw_end, "no clean-exit marker (atexit never ran)")
    # The whole point of the checkpoint: a killed title still says how much it
    # did, which is what "did rendering stop?" reduces to.
    check(counts.get("a") == "2-9" and counts.get("b") == "1",
          "counts survive _exit (periodic checkpoint, not atexit)")
    bad = sorted(k for k in expected_shared if counts.get(k) not in ("100-999", "1k-9k"))
    check(not bad,
          "threaded keys counted in the killed run too%s"
          % ("" if not bad else " (wrong: %s)" % bad))
    check(kv.get("scalar:answer") == 43 and kv.get("scalar:big") == 1234567890123,
          "scalars survive _exit too (they are written as they are set)")

    # --- the full record ----------------------------------------------------
    print("[milestone] --on (normal exit)")
    cp = run(exe, "--on", out)
    check(cp.returncode == 0, "driver ran")
    stream, counts, kv, saw_end = parse(out)

    keys = [k for _, k in stream]
    check(saw_end, "log is terminated with # end")
    check([o for o, _ in stream] == list(range(1, len(stream) + 1)),
          "ordinals are 1..N with no gaps")
    check(len(keys) == len(set(keys)), "no key is recorded twice")
    check(set(keys) == expected_all,
          "exactly the expected key set, no truncated or corrupted keys")
    check(keys[:3] == ["a", "b", "c"],
          "first-occurrence order is call order, not hash order")

    check(counts.get("a") == "2-9", "repeated key buckets by count (a x6 -> 2-9)")
    check(counts.get("b") == "1", "single occurrence buckets as 1")
    bad = sorted(k for k in expected_shared if counts.get(k) != "100-999")
    check(not bad,
          "every threaded key counted %d times -> 100-999%s"
          % (HITS_PER_KEY, "" if not bad else " (wrong: %s)" % bad))

    check(kv.get("scalar:answer") == 43, "scalar last-value-wins")
    check(kv.get("scalar:big") == 1234567890123, "64-bit scalar survives")

    if not args.keep:
        for p in (driver_c, exe, out):
            try:
                os.remove(p)
            except OSError:
                pass

    if FAILURES:
        print("\n[milestone] %d FAILED" % len(FAILURES))
        return 1
    print("\n[milestone] all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
